"""empty message

Revision ID: 16dd713d672d
Revises: a1b5c12648e7
Create Date: 2018-05-09 23:16:27.385979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dd713d672d'
down_revision = 'a1b5c12648e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dados', sa.Column('porta', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dados', 'porta')
    # ### end Alembic commands ###
