"""adição ultima visualização

Revision ID: 2e5184afa81a
Revises: 8f2b5bf2e697
Create Date: 2018-05-01 15:27:52.737153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5184afa81a'
down_revision = '8f2b5bf2e697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('ultima_visita', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'ultima_visita')
    # ### end Alembic commands ###
