"""tabela de usuários

Revision ID: 3670911384f9
Revises: b0675e257890
Create Date: 2018-04-22 15:13:28.350865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3670911384f9'
down_revision = 'b0675e257890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=140), nullable=True),
    sa.Column('produto', sa.String(length=20), nullable=True),
    sa.Column('cveid', sa.String(length=25), nullable=True),
    sa.Column('tipo', sa.String(length=25), nullable=True),
    sa.Column('datacorrecao', sa.String(length=50), nullable=True),
    sa.Column('nota', sa.String(length=10), nullable=True),
    sa.Column('acesso', sa.String(length=100), nullable=True),
    sa.Column('comentario', sa.String(length=5000), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servidor')
    # ### end Alembic commands ###
