"""empty message

Revision ID: cdd751375434
Revises: 4cc5a7b302a4
Create Date: 2018-05-01 17:47:40.007852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd751375434'
down_revision = '4cc5a7b302a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'last_seen')
    # ### end Alembic commands ###
